#!/usr/bin/env bash
# Displays informtation about subdomains.

# uncomment for debugging purposes.
#set -x

# for the checker to work please remove the colors.


# variables & parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

dig_cmd () {
	# func variables
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP${reset}"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_cmd "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$sub"
fi
