#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
