#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
#sudo ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
